// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PositionCommand.proto

package com.lemeng.proto;

public final class BaseCommand {
  private BaseCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.PositionCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required float position_x = 2;</code>
     */
    boolean hasPositionX();
    /**
     * <code>required float position_x = 2;</code>
     */
    float getPositionX();

    /**
     * <code>required float position_y = 3;</code>
     */
    boolean hasPositionY();
    /**
     * <code>required float position_y = 3;</code>
     */
    float getPositionY();

    /**
     * <code>required float position_z = 4;</code>
     */
    boolean hasPositionZ();
    /**
     * <code>required float position_z = 4;</code>
     */
    float getPositionZ();
  }
  /**
   * Protobuf type {@code message.PositionCommand}
   */
  public  static final class PositionCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.PositionCommand)
      PositionCommandOrBuilder {
    // Use PositionCommand.newBuilder() to construct.
    private PositionCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionCommand() {
      id_ = 0;
      positionX_ = 0F;
      positionY_ = 0F;
      positionZ_ = 0F;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              positionX_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              positionY_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              positionZ_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseCommand.internal_static_message_PositionCommand_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseCommand.internal_static_message_PositionCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PositionCommand.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int POSITION_X_FIELD_NUMBER = 2;
    private float positionX_;
    /**
     * <code>required float position_x = 2;</code>
     */
    public boolean hasPositionX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float position_x = 2;</code>
     */
    public float getPositionX() {
      return positionX_;
    }

    public static final int POSITION_Y_FIELD_NUMBER = 3;
    private float positionY_;
    /**
     * <code>required float position_y = 3;</code>
     */
    public boolean hasPositionY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float position_y = 3;</code>
     */
    public float getPositionY() {
      return positionY_;
    }

    public static final int POSITION_Z_FIELD_NUMBER = 4;
    private float positionZ_;
    /**
     * <code>required float position_z = 4;</code>
     */
    public boolean hasPositionZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float position_z = 4;</code>
     */
    public float getPositionZ() {
      return positionZ_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPositionX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPositionY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPositionZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, positionX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, positionY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, positionZ_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, positionX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, positionY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, positionZ_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PositionCommand)) {
        return super.equals(obj);
      }
      PositionCommand other = (PositionCommand) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasPositionX() == other.hasPositionX());
      if (hasPositionX()) {
        result = result && (
            Float.floatToIntBits(getPositionX())
            == Float.floatToIntBits(
                other.getPositionX()));
      }
      result = result && (hasPositionY() == other.hasPositionY());
      if (hasPositionY()) {
        result = result && (
            Float.floatToIntBits(getPositionY())
            == Float.floatToIntBits(
                other.getPositionY()));
      }
      result = result && (hasPositionZ() == other.hasPositionZ());
      if (hasPositionZ()) {
        result = result && (
            Float.floatToIntBits(getPositionZ())
            == Float.floatToIntBits(
                other.getPositionZ()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasPositionX()) {
        hash = (37 * hash) + POSITION_X_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getPositionX());
      }
      if (hasPositionY()) {
        hash = (37 * hash) + POSITION_Y_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getPositionY());
      }
      if (hasPositionZ()) {
        hash = (37 * hash) + POSITION_Z_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getPositionZ());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PositionCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PositionCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PositionCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PositionCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PositionCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PositionCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PositionCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PositionCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PositionCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PositionCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PositionCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PositionCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PositionCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.PositionCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.PositionCommand)
        PositionCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseCommand.internal_static_message_PositionCommand_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseCommand.internal_static_message_PositionCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PositionCommand.class, Builder.class);
      }

      // Construct using com.lemeng.proto.BaseCommand.PositionCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        positionX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        positionY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        positionZ_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseCommand.internal_static_message_PositionCommand_descriptor;
      }

      public PositionCommand getDefaultInstanceForType() {
        return PositionCommand.getDefaultInstance();
      }

      public PositionCommand build() {
        PositionCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PositionCommand buildPartial() {
        PositionCommand result = new PositionCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.positionX_ = positionX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.positionY_ = positionY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.positionZ_ = positionZ_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PositionCommand) {
          return mergeFrom((PositionCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PositionCommand other) {
        if (other == PositionCommand.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPositionX()) {
          setPositionX(other.getPositionX());
        }
        if (other.hasPositionY()) {
          setPositionY(other.getPositionY());
        }
        if (other.hasPositionZ()) {
          setPositionZ(other.getPositionZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasPositionX()) {
          return false;
        }
        if (!hasPositionY()) {
          return false;
        }
        if (!hasPositionZ()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PositionCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PositionCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private float positionX_ ;
      /**
       * <code>required float position_x = 2;</code>
       */
      public boolean hasPositionX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float position_x = 2;</code>
       */
      public float getPositionX() {
        return positionX_;
      }
      /**
       * <code>required float position_x = 2;</code>
       */
      public Builder setPositionX(float value) {
        bitField0_ |= 0x00000002;
        positionX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float position_x = 2;</code>
       */
      public Builder clearPositionX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        positionX_ = 0F;
        onChanged();
        return this;
      }

      private float positionY_ ;
      /**
       * <code>required float position_y = 3;</code>
       */
      public boolean hasPositionY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float position_y = 3;</code>
       */
      public float getPositionY() {
        return positionY_;
      }
      /**
       * <code>required float position_y = 3;</code>
       */
      public Builder setPositionY(float value) {
        bitField0_ |= 0x00000004;
        positionY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float position_y = 3;</code>
       */
      public Builder clearPositionY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        positionY_ = 0F;
        onChanged();
        return this;
      }

      private float positionZ_ ;
      /**
       * <code>required float position_z = 4;</code>
       */
      public boolean hasPositionZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float position_z = 4;</code>
       */
      public float getPositionZ() {
        return positionZ_;
      }
      /**
       * <code>required float position_z = 4;</code>
       */
      public Builder setPositionZ(float value) {
        bitField0_ |= 0x00000008;
        positionZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float position_z = 4;</code>
       */
      public Builder clearPositionZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        positionZ_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.PositionCommand)
    }

    // @@protoc_insertion_point(class_scope:message.PositionCommand)
    private static final PositionCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PositionCommand();
    }

    public static PositionCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PositionCommand>
        PARSER = new com.google.protobuf.AbstractParser<PositionCommand>() {
      public PositionCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PositionCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionCommand> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PositionCommand> getParserForType() {
      return PARSER;
    }

    public PositionCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionListCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.PositionListCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    java.util.List<PositionCommand>
        getPositionListList();
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    PositionCommand getPositionList(int index);
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    int getPositionListCount();
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    java.util.List<? extends PositionCommandOrBuilder>
        getPositionListOrBuilderList();
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    PositionCommandOrBuilder getPositionListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code message.PositionListCommand}
   */
  public  static final class PositionListCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.PositionListCommand)
      PositionListCommandOrBuilder {
    // Use PositionListCommand.newBuilder() to construct.
    private PositionListCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionListCommand() {
      positionList_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionListCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                positionList_ = new java.util.ArrayList<PositionCommand>();
                mutable_bitField0_ |= 0x00000001;
              }
              positionList_.add(
                  input.readMessage(PositionCommand.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          positionList_ = java.util.Collections.unmodifiableList(positionList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseCommand.internal_static_message_PositionListCommand_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseCommand.internal_static_message_PositionListCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PositionListCommand.class, Builder.class);
    }

    public static final int POSITIONLIST_FIELD_NUMBER = 1;
    private java.util.List<PositionCommand> positionList_;
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    public java.util.List<PositionCommand> getPositionListList() {
      return positionList_;
    }
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    public java.util.List<? extends PositionCommandOrBuilder>
        getPositionListOrBuilderList() {
      return positionList_;
    }
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    public int getPositionListCount() {
      return positionList_.size();
    }
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    public PositionCommand getPositionList(int index) {
      return positionList_.get(index);
    }
    /**
     * <code>repeated .message.PositionCommand positionList = 1;</code>
     */
    public PositionCommandOrBuilder getPositionListOrBuilder(
        int index) {
      return positionList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPositionListCount(); i++) {
        if (!getPositionList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < positionList_.size(); i++) {
        output.writeMessage(1, positionList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < positionList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, positionList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PositionListCommand)) {
        return super.equals(obj);
      }
      PositionListCommand other = (PositionListCommand) obj;

      boolean result = true;
      result = result && getPositionListList()
          .equals(other.getPositionListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPositionListCount() > 0) {
        hash = (37 * hash) + POSITIONLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPositionListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PositionListCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PositionListCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PositionListCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PositionListCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PositionListCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PositionListCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PositionListCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PositionListCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PositionListCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PositionListCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PositionListCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PositionListCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PositionListCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.PositionListCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.PositionListCommand)
        PositionListCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseCommand.internal_static_message_PositionListCommand_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseCommand.internal_static_message_PositionListCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PositionListCommand.class, Builder.class);
      }

      // Construct using com.lemeng.proto.BaseCommand.PositionListCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPositionListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (positionListBuilder_ == null) {
          positionList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          positionListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseCommand.internal_static_message_PositionListCommand_descriptor;
      }

      public PositionListCommand getDefaultInstanceForType() {
        return PositionListCommand.getDefaultInstance();
      }

      public PositionListCommand build() {
        PositionListCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PositionListCommand buildPartial() {
        PositionListCommand result = new PositionListCommand(this);
        int from_bitField0_ = bitField0_;
        if (positionListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            positionList_ = java.util.Collections.unmodifiableList(positionList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.positionList_ = positionList_;
        } else {
          result.positionList_ = positionListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PositionListCommand) {
          return mergeFrom((PositionListCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PositionListCommand other) {
        if (other == PositionListCommand.getDefaultInstance()) return this;
        if (positionListBuilder_ == null) {
          if (!other.positionList_.isEmpty()) {
            if (positionList_.isEmpty()) {
              positionList_ = other.positionList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePositionListIsMutable();
              positionList_.addAll(other.positionList_);
            }
            onChanged();
          }
        } else {
          if (!other.positionList_.isEmpty()) {
            if (positionListBuilder_.isEmpty()) {
              positionListBuilder_.dispose();
              positionListBuilder_ = null;
              positionList_ = other.positionList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              positionListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPositionListFieldBuilder() : null;
            } else {
              positionListBuilder_.addAllMessages(other.positionList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPositionListCount(); i++) {
          if (!getPositionList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PositionListCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PositionListCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PositionCommand> positionList_ =
        java.util.Collections.emptyList();
      private void ensurePositionListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          positionList_ = new java.util.ArrayList<PositionCommand>(positionList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PositionCommand, PositionCommand.Builder, PositionCommandOrBuilder> positionListBuilder_;

      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public java.util.List<PositionCommand> getPositionListList() {
        if (positionListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(positionList_);
        } else {
          return positionListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public int getPositionListCount() {
        if (positionListBuilder_ == null) {
          return positionList_.size();
        } else {
          return positionListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public PositionCommand getPositionList(int index) {
        if (positionListBuilder_ == null) {
          return positionList_.get(index);
        } else {
          return positionListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder setPositionList(
          int index, PositionCommand value) {
        if (positionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionListIsMutable();
          positionList_.set(index, value);
          onChanged();
        } else {
          positionListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder setPositionList(
          int index, PositionCommand.Builder builderForValue) {
        if (positionListBuilder_ == null) {
          ensurePositionListIsMutable();
          positionList_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder addPositionList(PositionCommand value) {
        if (positionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionListIsMutable();
          positionList_.add(value);
          onChanged();
        } else {
          positionListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder addPositionList(
          int index, PositionCommand value) {
        if (positionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionListIsMutable();
          positionList_.add(index, value);
          onChanged();
        } else {
          positionListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder addPositionList(
          PositionCommand.Builder builderForValue) {
        if (positionListBuilder_ == null) {
          ensurePositionListIsMutable();
          positionList_.add(builderForValue.build());
          onChanged();
        } else {
          positionListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder addPositionList(
          int index, PositionCommand.Builder builderForValue) {
        if (positionListBuilder_ == null) {
          ensurePositionListIsMutable();
          positionList_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder addAllPositionList(
          Iterable<? extends PositionCommand> values) {
        if (positionListBuilder_ == null) {
          ensurePositionListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, positionList_);
          onChanged();
        } else {
          positionListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder clearPositionList() {
        if (positionListBuilder_ == null) {
          positionList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          positionListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public Builder removePositionList(int index) {
        if (positionListBuilder_ == null) {
          ensurePositionListIsMutable();
          positionList_.remove(index);
          onChanged();
        } else {
          positionListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public PositionCommand.Builder getPositionListBuilder(
          int index) {
        return getPositionListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public PositionCommandOrBuilder getPositionListOrBuilder(
          int index) {
        if (positionListBuilder_ == null) {
          return positionList_.get(index);  } else {
          return positionListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public java.util.List<? extends PositionCommandOrBuilder>
           getPositionListOrBuilderList() {
        if (positionListBuilder_ != null) {
          return positionListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(positionList_);
        }
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public PositionCommand.Builder addPositionListBuilder() {
        return getPositionListFieldBuilder().addBuilder(
            PositionCommand.getDefaultInstance());
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public PositionCommand.Builder addPositionListBuilder(
          int index) {
        return getPositionListFieldBuilder().addBuilder(
            index, PositionCommand.getDefaultInstance());
      }
      /**
       * <code>repeated .message.PositionCommand positionList = 1;</code>
       */
      public java.util.List<PositionCommand.Builder>
           getPositionListBuilderList() {
        return getPositionListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PositionCommand, PositionCommand.Builder, PositionCommandOrBuilder>
          getPositionListFieldBuilder() {
        if (positionListBuilder_ == null) {
          positionListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PositionCommand, PositionCommand.Builder, PositionCommandOrBuilder>(
                  positionList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          positionList_ = null;
        }
        return positionListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.PositionListCommand)
    }

    // @@protoc_insertion_point(class_scope:message.PositionListCommand)
    private static final PositionListCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PositionListCommand();
    }

    public static PositionListCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PositionListCommand>
        PARSER = new com.google.protobuf.AbstractParser<PositionListCommand>() {
      public PositionListCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PositionListCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionListCommand> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PositionListCommand> getParserForType() {
      return PARSER;
    }

    public PositionListCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.LoginCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();
  }
  /**
   * Protobuf type {@code message.LoginCommand}
   */
  public  static final class LoginCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.LoginCommand)
      LoginCommandOrBuilder {
    // Use LoginCommand.newBuilder() to construct.
    private LoginCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginCommand() {
      username_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              username_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseCommand.internal_static_message_LoginCommand_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseCommand.internal_static_message_LoginCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoginCommand.class, Builder.class);
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile Object username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoginCommand)) {
        return super.equals(obj);
      }
      LoginCommand other = (LoginCommand) obj;

      boolean result = true;
      result = result && (hasUsername() == other.hasUsername());
      if (hasUsername()) {
        result = result && getUsername()
            .equals(other.getUsername());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoginCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoginCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoginCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.LoginCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.LoginCommand)
        LoginCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseCommand.internal_static_message_LoginCommand_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseCommand.internal_static_message_LoginCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoginCommand.class, Builder.class);
      }

      // Construct using com.lemeng.proto.BaseCommand.LoginCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseCommand.internal_static_message_LoginCommand_descriptor;
      }

      public LoginCommand getDefaultInstanceForType() {
        return LoginCommand.getDefaultInstance();
      }

      public LoginCommand build() {
        LoginCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LoginCommand buildPartial() {
        LoginCommand result = new LoginCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoginCommand) {
          return mergeFrom((LoginCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoginCommand other) {
        if (other == LoginCommand.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoginCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoginCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.LoginCommand)
    }

    // @@protoc_insertion_point(class_scope:message.LoginCommand)
    private static final LoginCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginCommand();
    }

    public static LoginCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<LoginCommand>
        PARSER = new com.google.protobuf.AbstractParser<LoginCommand>() {
      public LoginCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginCommand> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginCommand> getParserForType() {
      return PARSER;
    }

    public LoginCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_PositionCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_PositionCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_PositionListCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_PositionListCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_LoginCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_LoginCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025PositionCommand.proto\022\007message\"Y\n\017Posi" +
      "tionCommand\022\n\n\002id\030\001 \002(\005\022\022\n\nposition_x\030\002 " +
      "\002(\002\022\022\n\nposition_y\030\003 \002(\002\022\022\n\nposition_z\030\004 " +
      "\002(\002\"E\n\023PositionListCommand\022.\n\014positionLi" +
      "st\030\001 \003(\0132\030.message.PositionCommand\" \n\014Lo" +
      "ginCommand\022\020\n\010username\030\001 \001(\tB\037\n\020com.leme" +
      "ng.protoB\013BaseCommand"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_PositionCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_PositionCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_PositionCommand_descriptor,
        new String[] { "Id", "PositionX", "PositionY", "PositionZ", });
    internal_static_message_PositionListCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_PositionListCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_PositionListCommand_descriptor,
        new String[] { "PositionList", });
    internal_static_message_LoginCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_LoginCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_LoginCommand_descriptor,
        new String[] { "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
